# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question_description', models.TextField()),
                ('test_inputs', models.CharField(max_length=200)),
                ('test_outputs', models.CharField(max_length=200)),
                ('java_equivalent', models.TextField()),
                ('answer_code', models.TextField()),
                ('hints', models.TextField()),
            ],
        ),
    ]
