# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-22 17:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_name',
            field=models.CharField(default='null', max_length=200),
            preserve_default=False,
        ),
    ]
