# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0003_auto_20171117_2009'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='question_id',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
