# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-20 23:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0004_exercise_question_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='question_id',
        ),
    ]
