# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 00:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0008_auto_20171121_0037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercise',
            name='slug',
        ),
    ]
