# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-21 19:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0011_auto_20171121_0051'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercise',
            name='category',
            field=models.CharField(default=0, max_length=200),
            preserve_default=False,
        ),
    ]
