# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-11-27 03:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exercises', '0012_exercise_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='test_outputs',
            field=models.TextField(),
        ),
    ]
